export const gameConsoles = [
    {
      id: 1,
      img: "https://hotline.ua/img/tx/230/2304447945.jpg",
      title: "PlayStation 5",
      text: "Нова ігрова консоль з потужним апаратним забезпеченням.",
      price: 499.99,
    },
    {
      id: 2,
      img: "https://m.media-amazon.com/images/I/61v9UBUyWYL.jpg",
      title: "Xbox Series X",
      text: "Ігрова консоль з високою продуктивністю та широким набором ігор.",
      price: 599.99,
    },
    {
      id: 3,
      img: "https://game-shop.com.ua/uploads/Nintendo%20Switch%20(OLED%20model)%20White%20Set-6.jpg",
      title: "Nintendo Switch",
      text: "Переносна ігрова консоль з унікальними ігровими можливостями.",
      price: 299.99,
    },
    {
      id: 4,
      img: "https://images.prom.ua/4610669839_w640_h640_4610669839.jpg",
      title: "PlayStation 4",
      text: "Попередня версія ігрової консолі PlayStation з великим вибором ігор.",
      price: 299.99,
    },
    {
      id: 5,
      img: "https://hotline.ua/img/tx/179/1795645255.jpg",
      title: "Xbox One",
      text: "Популярна ігрова консоль від Microsoft з великою гральною спільнотою.",
      price: 249.99,
    },
    {
      id: 6,
      img: "https://hotline.ua/img/tx/720/7207935.jpg",
      title: "Nintendo 3DS",
      text: "Портативна ігрова консоль з великим вибором ігор у 3D форматі.",
      price: 199.99,
    },
    {
      id: 7,
      img: "https://hotline.ua/img/tx/276/276488645.jpg",
      title: "PlayStation Vita",
      text: "Переносна ігрова консоль зі зручними функціями та іграми.",
      price: 179.99,
    },
    {
      id: 8,
      img: "https://hotline.ua/img/tx/800/8009095.jpg",
      title: "Xbox 360",
      text: "Популярна попередня версія ігрової консолі Xbox з широким набором ігор.",
      price: 149.99,
    },
    {
      id: 9,
      img: "https://gamespot.com.ua/image/cache/catalog/Gamespotcontent/Wii%20U/Nintendo%20Wii%20U/377780410_w800_h640_nintendo_wii_hotplay-500x500.jpg",
      title: "Nintendo Wii U",
      text: "Консоль з унікальними контролерами та іграми для всієї родини.",
      price: 199.99,
    },
    {
      id: 10,
      img: "https://m.media-amazon.com/images/I/71SYFHVvvRL.jpg",
      title: "Sega Genesis Mini",
      text: "Мініатюрна версія легендарної ігрової консолі Sega Genesis з популярними іграми.",
      price: 79.99,
    }
  ];